#!/bin/csh -f
if (-e ../Semant.java) then
  ../lexer $* | ../parser $* | java -classpath ../../class/cs143/cool/lib:..:/usr/java/lib/rt.jar Semant $*
else
  ../lexer $* | ../parser $* | ../semant $*
endif

